import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Check, ChevronDown, Download, FileArchive, FileSpreadsheet, Github, Moon, ShieldCheck, Sparkles, Sun, Trash2, UploadCloud, X, Zap } from 'lucide-react';
import JSZip from 'jszip'; import { conversionGroups, tools } from './config/tools'; import type { ConversionSource, ImageFormat } from './config/tools'; import type { OutputFile, Status, ToolId } from './types'; import { csvToExcel, excelToCsv, excelToMarkdown, previewSheet, sheetNames } from './converters/spreadsheet'; import { convertImage, imagesToPdf } from './converters/images';
import { videoToMp3 } from './converters/media';
const fmt=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
const stem=(n:string)=>n.replace(/\.[^.]+$/,'');
export default function App(){
 const [dark,setDark]=useState(()=>localStorage.theme==='dark'); const [tool,setTool]=useState<ToolId>('excel-csv'); const [source,setSource]=useState<ConversionSource>('excel'); const [files,setFiles]=useState<File[]>([]); const [outputs,setOutputs]=useState<OutputFile[]>([]); const [status,setStatus]=useState<Status>('idle'); const [progressMessage,setProgressMessage]=useState('変換しています…'); const [error,setError]=useState(''); const [drag,setDrag]=useState(false); const [delimiter,setDelimiter]=useState(','); const [encoding,setEncoding]=useState('bom'); const [firstRowAsHeader,setFirstRowAsHeader]=useState(true); const [format,setFormat]=useState<'png'|'jpeg'|'webp'>('webp'); const [sheets,setSheets]=useState<string[]>([]); const [sheet,setSheet]=useState(''); const [preview,setPreview]=useState<string[][]>([]); const input=useRef<HTMLInputElement>(null); const selected=tools.find(x=>x.id===tool)!;
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.theme=dark?'dark':'light'},[dark]);
 useEffect(()=>{setFiles([]);clearOutputs();setPreview([]);setSheets([])},[tool,source]);
 const clearOutputs=()=>{outputs.forEach(o=>URL.revokeObjectURL(o.url));setOutputs([]);setStatus('idle')};
 const sourceGroup=conversionGroups.find(group=>group.id===source)!;
 const chooseSource=(next:ConversionSource)=>{const group=conversionGroups.find(item=>item.id===next)!;const output=group.outputs[0];setSource(next);if(output.format)setFormat(output.format);setTool(output.tool)};
 const chooseOutput=(nextTool:ToolId,nextFormat?:ImageFormat)=>{if(nextFormat)setFormat(nextFormat);setTool(nextTool)};
 const add=async(list:FileList|File[])=>{const next=[...files,...Array.from(list)];setFiles(next);clearOutputs();if((tool==='excel-csv'||tool==='excel-markdown')&&next[0]){try{const ns=await sheetNames(next[0]);setSheets(ns);setSheet(ns[0]);setPreview(await previewSheet(next[0],ns[0]))}catch{setError('Excelファイルを読み込めませんでした')}}};
 const changeSheet=async(s:string)=>{setSheet(s);setPreview(await previewSheet(files[0],s))};
 const remove=(i:number)=>{setFiles(f=>f.filter((_,n)=>n!==i));clearOutputs()};
 const run=async()=>{setStatus('processing');setProgressMessage('変換しています…');setError('');try{const result:OutputFile[]=[];if(tool==='images-pdf'){const blob=await imagesToPdf(files);result.push({name:'QuickConvert_images.pdf',blob,url:URL.createObjectURL(blob)})}else for(const f of files){let blob:Blob,name:string;if(tool==='excel-csv'){blob=await excelToCsv(f,files.length===1?sheet:undefined,delimiter,encoding);name=stem(f.name)+'.csv'}else if(tool==='csv-excel'){blob=await csvToExcel(f,delimiter);name=stem(f.name)+'.xlsx'}else if(tool==='excel-markdown'){blob=await excelToMarkdown(f,files.length===1?sheet:undefined,firstRowAsHeader);name=stem(f.name)+'.md'}else if(tool==='video-audio'){blob=await videoToMp3(f,setProgressMessage);name=stem(f.name)+'.mp3'}else{blob=await convertImage(f,format);name=stem(f.name)+'.'+(format==='jpeg'?'jpg':format)}result.push({name,blob,url:URL.createObjectURL(blob)})}setOutputs(result);setStatus('done')}catch(e){setError(e instanceof Error?e.message:'変換中にエラーが発生しました');setStatus('error')}};
 const zip=async()=>{const z=new JSZip();outputs.forEach(o=>z.file(o.name,o.blob));const b=await z.generateAsync({type:'blob'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='QuickConvert_files.zip';a.click();URL.revokeObjectURL(a.href)};
 return <div className="app"><header><a className="brand" href="#"><span className="logo"><Zap size={20}/></span><b>QuickConvert</b></a><nav><a href="#tools">変換ツール</a><a href="#how">使い方</a><a href="#privacy">プライバシー</a></nav><div className="head-actions"><button className="icon-btn" onClick={()=>setDark(!dark)} aria-label="テーマ切替">{dark?<Sun/>:<Moon/>}</button><a className="github" href="https://github.com" aria-label="GitHub"><Github/></a></div></header>
 <main><section className="hero"><div className="eyebrow"><Sparkles size={14}/> ブラウザだけで、すぐ変換</div><h1>ファイル変換を、<br/><em>もっと軽やかに。</em></h1><p>Excel、CSV、画像、動画をドラッグ＆ドロップ。<br/>アップロード不要で、安全・高速に変換できます。</p><div className="privacy-pill"><ShieldCheck size={17}/><span><b>100% プライベート</b> — ファイルは外部に送信されません</span></div></section>
 <section className="workspace" id="tools"><div className="format-picker"><div className="format-group"><span className="format-label">変換前</span><div className="format-options">{conversionGroups.map(group=><button key={group.id} className={source===group.id?'active':''} onClick={()=>chooseSource(group.id)}><group.icon size={17}/>{group.label}</button>)}</div></div><ArrowRight className="format-arrow"/><div className="format-group output-group"><span className="format-label">変換後</span><div className="format-options">{sourceGroup.outputs.map(output=><button key={output.label} className={tool===output.tool&&(!output.format||format===output.format)?'active':''} onClick={()=>chooseOutput(output.tool,output.format)}>{output.label}</button>)}</div></div></div><div className="panel">
  <div className={`drop ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);add(e.dataTransfer.files)}} onClick={()=>input.current?.click()}><input ref={input} type="file" accept={sourceGroup.accept} multiple={selected.multiple} onChange={e=>e.target.files&&add(e.target.files)}/><div className="upload-icon"><UploadCloud/></div><h2>ファイルをここにドロップ</h2><p>または</p><button className="choose">ファイルを選択 <ArrowRight size={16}/></button><small>対応形式：{sourceGroup.accept.replaceAll('image/','').replaceAll(',',' / ').toUpperCase()} ・ 複数選択可</small></div>
  {files.length>0&&<div className="file-area"><div className="section-title"><div><h3>選択したファイル</h3><span>{files.length}件</span></div><button onClick={()=>{setFiles([]);clearOutputs()}}>すべて削除</button></div><div className="file-list">{files.map((f,i)=><div className="file-row" key={f.name+i}><span className="file-icon"><FileSpreadsheet/></span><div className="file-meta"><b>{f.name}</b><small>{f.type.split('/').pop()?.toUpperCase()||'FILE'} ・ {fmt(f.size)}</small></div><span className="ready"><Check/>準備完了</span><button className="remove" onClick={()=>remove(i)}><X/></button></div>)}</div>
   <div className="settings"><h3>変換設定</h3>{(tool==='excel-csv'||tool==='excel-markdown')&&files.length===1&&<label>シート<select value={sheet} onChange={e=>changeSheet(e.target.value)}>{sheets.map(s=><option key={s}>{s}</option>)}</select><ChevronDown/></label>}{(tool==='excel-csv'||tool==='csv-excel')&&<label>区切り文字<select value={delimiter} onChange={e=>setDelimiter(e.target.value)}><option value=",">カンマ（,）</option><option value={'\t'}>タブ</option><option value=";">セミコロン（;）</option></select><ChevronDown/></label>}{tool==='excel-csv'&&<label>文字コード<select value={encoding} onChange={e=>setEncoding(e.target.value)}><option value="utf8">UTF-8</option><option value="bom">UTF-8（BOM付き）</option><option value="sjis">Shift_JIS</option></select><ChevronDown/></label>}{tool==='excel-markdown'&&<label>先頭行<select value={firstRowAsHeader?'header':'data'} onChange={e=>setFirstRowAsHeader(e.target.value==='header')}><option value="header">見出しとして使用</option><option value="data">データとして使用</option></select><ChevronDown/></label>}{tool==='image-format'&&<label>変換後の形式<select value={format} onChange={e=>setFormat(e.target.value as typeof format)}><option value="png">PNG</option><option value="jpeg">JPEG</option><option value="webp">WebP</option></select><ChevronDown/></label>}</div>
   {preview.length>0&&<div className="preview"><h3>プレビュー <span>先頭20行</span></h3><div className="table-wrap"><table><tbody>{preview.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div></div>}
   <button className="convert" disabled={status==='processing'} onClick={run}>{status==='processing'?<><span className="spinner"/>{progressMessage}</>:<><Zap/>変換する</>}</button>
  </div>}
  {error&&<div className="notice error">{error}</div>}{status==='done'&&<div className="results"><div className="done-head"><span><Check/></span><div><h3>変換が完了しました</h3><p>{outputs.length}件のファイルを作成しました</p></div></div>{outputs.map(o=><a className="result-row" href={o.url} download={o.name} key={o.name}><span>{o.name}</span><Download/></a>)}<div className="result-actions">{outputs.length>1&&<button onClick={zip}><FileArchive/>ZIPで一括ダウンロード</button>}<button className="discard" onClick={clearOutputs}><Trash2/>変換ファイルを破棄</button></div></div>}
 </div></section>
 <section className="features" id="privacy"><article><span className="feature-icon blue"><ShieldCheck/></span><h3>ファイルは外部に送信されません</h3><p>すべての変換処理は、お使いのブラウザ内で完結します。</p></article><article><span className="feature-icon violet"><Zap/></span><h3>インストール不要</h3><p>ソフトのダウンロードなし。ブラウザを開くだけですぐ使えます。</p></article><article><span className="feature-icon orange"><FileArchive/></span><h3>まとめて一括変換</h3><p>複数ファイルを一度に変換。ZIPでまとめてダウンロードできます。</p></article></section></main>
 <footer><a className="brand" href="#"><span className="logo"><Zap size={18}/></span><b>QuickConvert</b></a><p>ファイル変換を、もっとシンプルに。</p><span>© 2026 QuickConvert</span></footer></div>
}
